language: objective-c
before_install:
  - brew update
  - brew upgrade xctool
  - gem update cocoapods
xcode_workspace: pop.xcworkspace
xcode_scheme: pop
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1
